# Generated by Django 6.0 on 2026-01-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('file', models.FileField(upload_to='documents/')),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
