# Generated by Django 6.0 on 2026-01-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('REPORT', 'Report'), ('LEGAL', 'Legal'), ('FINANCE', 'Finance'), ('MEDIA', 'Media')], default='MEDIA'),
            preserve_default=False,
        ),
    ]
