# Generated by Django 6.0 on 2026-01-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
