# Generated by Django 6.0 on 2025-12-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('pub_date', models.DateField(verbose_name='Published Date')),
            ],
        ),
    ]
